### ISSUE TITLE
Could you please provide the complete dataset?

### ISSUE THREAD

**Issue by laizef** [LarsBentsen/FFTransformer#1]
Hi, your work and code are truly impressive to me. I'm interested in the full dataset you used, but I don't know to get access to it . Would you be able to provide me with the full dataset or just share the code you used to access with API? I would greatly appreciate it and it would be incredibly helpful for me. Thank you!

**Comment by LarsBentsen** [comment]
Hi! I am very glad that you found the work interesting. 
With regards to the dataset, I cannot publish the dataset I used, but you can create a user and get more information on how to use the Frost API here: https://frost.met.no/howto.html. 
I've created a data retrieval example in './dataset_example/RetrieveExample.py' that should guide you as to how to download data using the Frost API. 
I will close the issue, but please re-open it if you have any other issues or questions. 
Also, remember to cite our paper if you find it useful for your work, thanks!

**Comment by anothersin** [comment]
Hi, thanks for giving the RetrieveExample.py, but I cannot get the data from the same stations as you providing.

The following data is accessed from the RetrieveExample.py and different from [dataset_example/WindData/dataset/station_info.csv](url)

dist_tar        id        lat        lon                      name  

0    86685.837591   SN34130  58.856500   9.574500                JOMFRULAND   
1    93115.662183   SN35860  58.636200   9.147800                LYNGØR FYR   
2    94082.828413   SN35340  58.718300   9.211100        RISØR BRANNSTASJON   
3    98873.469205   SN30242  58.992830   9.923170          FV301 BERG KIRKE   
4    99086.979461   SN34095  58.981700   9.606800          E18 STOKKEBAKKEN   
5   100246.282259  SN604100  57.736389  10.631667                SKAGEN FYR   
6   101438.046930   SN34115  58.967500   9.483700        E18 SPRANGFOSS BRU   
7   102744.588356   SN29950  58.968800  10.148000               SVENNER FYR   
8   105359.066183   SN34370  58.924550   9.312600            E18 GJERDEMYRA   
9   109547.606187   SN35090  58.803700   9.098000                  EIKELAND   
10  110235.427818  SN603000  57.096389   9.850556      FLYVESTATION AALBORG   
11  111640.650721   SN35110  58.851000   9.119670         E18 ØSTERHOLTHEIA   
12  120311.363309   SN35210  58.870000   9.026300  GJERSTAD JERNBANESTASJON 


Could you please give the deatil code for geting and processing data as same as your paper?
