### ISSUE TITLE
About the model input

### ISSUE THREAD

**Issue by tkjUser** [LarsBentsen/FFTransformer#6]
The input in the figure below is multiple features (such as wind speed, air temperature, air pressure, etc.).
![image](https://github.com/LarsBentsen/FFTransformer/assets/89716632/2c48dd7e-3323-4492-8a26-6bddfc80dd35)
In the MDWD decomposition step, should only wind speed be decomposed or all features be decomposed using MDWD? What is the difference in performance between the decomposition of all features and only the wind speed?

**Comment by LarsBentsen** [comment]
Hi, 
In the published code, all input features are decomposed independently. For the encoder, this equates to all the available input features, while the decoder (here) only takes the wind speed measurements as input. Note that the decoder is not used for the graph-based models, but was included for completeness. When performing the research, I believe we experimented with only decomposing the wind speed series as well, but obtained slightly better results decomposing all input time-series. Unfortunately, I cannot remember the exact results and I would advise you to experiment with this for your own research/implementation. 
As a final note, the MDWD implementation is quite slow/a current bottleneck and some additional work to speed up the decomposition (or perform the decomposition once on the entire dataset before starting training) could be useful. 
I will close this issue now, but please feel free to re-open it if this did not answer all your questions! :)
